# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will run the python script, run Pylint on the
# python code, and then build a Docker image that contains the 
# Python app

name: Dockerize Python App

on: #Event is triggered ( series of commands when a  code is pushed or PR is created) testing - testing
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs: #Jobs - Every Job runs in 
  build:

    runs-on: ${{matrix.os}} #ubuntu-latest (Docker preinstalled),windows-latest,macOs-latest #Runs on ubuntu, windows or mac OS
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    # Run Python app to see output in log (sample dice roll)
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python main.py

    - name: all-lints
      uses: ricardochaves/python-lint@master
      with:
        python-root-list: "tests"
      
    - name: Build and push docker image to Docker Hub # docker login cred     docker build     docker tag # https://github.com/marketplace/actions/docker-build-push-action
      uses: mr-smithers-excellent/docker-build-push@v6 #action with v6
      with:
        image: don31658/githubactionspython #Parameters to overwrite Docker ID and repo name
        tags: v1, latest
        dockerfile: ./Dockerfile
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
